point_cloud_topic: "/none"
depth_image_topic: "/camera/aligned_depth_to_color/image_raw"
sensor_frame_id: "camera_color_optical_frame"
map_frame_id: "map"
robot_base_frame_id: "odom"
robot_pose_with_covariance_topic: "/cassie/pose"
robot_pose_cache_size: 200
track_point_frame_id: "odom"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0

#// remap tfs
#// odom -> map
#// cassie/torso -> odom

